### ISSUE TITLE
Vue i18n in javascript files?

### ISSUE THREAD

**Issue by danielgara** [SPLA/VARIAMOS-WEB#1]
https://github.com/SPLA/VARIAMOS-WEB/blob/39c604d7be0dc433fe1cb354911826821c41e224/src/assets/js/models/model_main.js#L8

How to apply vue i18n rules to JavaScript files.

**Comment by lufe089** [comment]
I think you should turn the javascript file as a vue component, then import the internationalization configuration

**Comment by danielgara** [comment]
Thanks Luisa, 

I found a easy way, just importing a JS file in the APP component.
