### ISSUE TITLE
Cotalogue - this line has to be modified

### ISSUE THREAD

**Issue by danielgara** [SPLA/VARIAMOS-WEB#26]
https://github.com/SPLA/VARIAMOS-WEB/blob/b016751c669f7b82ed7d6d02bf5ecc30fdd9d6a0/src/components/cotalogue.vue#L195

Hi Yan, If I understood, if I open any folder the first time (domain, application or adaptation) it will display the feature model.

But what happen if I disabled the feature model in the global_info.js -> for example if I put that the feature model will only appear in the domain folder but not in the application or adaptation. And I open the application folder? It will show me feature model anyway? right?

I think we should improve this code, with the use of the global_info file. Take the information from the models, check the first model that was selected to appear at the folder that I am opening, and show that model. If no models are selected to appear in a specific folder. For example any of the models were selected to appear in adaptation. Then, instead of showing a model we should show a message saying, not available models for this folder at this time.

Let me know if you have any suggestion or idea. Thanks.

**Comment by 6ucky** [comment]
OK, Daniel. You are right. I will change it.
